version: '3.8'

services:
  db:
    image: postgres:12.14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quote_editor_db
    ports:
      - "5432:5432"
