default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: 127.0.0.1
  port: 5432
  password: password

development:
  <<: *default
  database: quote_editor_db

test:
  <<: *default
  database: quote_editor_test
